version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3007:3006"
    volumes:
      - /data/mysql:/data/mysql
    env_file:
      - .env

  todoer:
    depends_on:
      - mysql
    container_name: todoer
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - '3000:3000'
    command: npm run dev
    restart: on-failure