version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - /data/mysql:/data/mysql
    env_file:
      - .env

  app:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
      - /src/node_modules
    ports:
      - "3000:3000"
